#!/usr/bin/env sh
set -e
cd "$(git rev-parse --show-toplevel)"
echo "Running pre-commit checks..."
UNFORMATTED=$(gofmt -l . 2>&1)
if [ -n "$UNFORMATTED" ]; then
  echo "ERROR: Files need formatting:" && echo "$UNFORMATTED" && exit 1
fi
go vet ./...
go build ./...
echo "All checks passed."
